In [0]:
import numpy as np

In [0]:
#http://www.utc.fr/~jlaforet/Suppl/python-cheatsheets.pdf

In [0]:
#Why is numpy used?
#Speed
#Scientific Computing Inbuilt
#Less Header -> Less Memory Usage

In [0]:
#How to create numpy arrays?
#Numpy arrays are predefined in size

In [0]:
#How to create numpy array
a = np.array([1,2,3])

In [6]:
print(a)

[1 2 3]


In [7]:
print(type(a))

<class 'numpy.ndarray'>


In [0]:
num = [1,2,3]
b = np.array(num)

In [9]:
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [10]:
details = [1,"Chirag",30.6]
c = np.array(details)
print(c)

['1' 'Chirag' '30.6']


In [11]:
#How to check datatype of a np array?
print(a.dtype) #prints the datatype of every value stored in a

int64


In [12]:
print(c.dtype)

<U21


In [0]:
#2-D arrays in numpy
d = np.array([[1,2,3],[4,5,6]]) #2D array since it's list of list

In [14]:
print(d)

[[1 2 3]
 [4 5 6]]


In [15]:
#Why don't you give me shape of this array?
print(d.shape)

(2, 3)


In [16]:
#What's the value at row - 0 and column - 0
print(d[0][0])

1


In [17]:
print(d[0,0]) #Pythonic way of writing it

1


In [0]:
e = np.array([[1,2,3.0],[4,5,6],[7,8,9]])

In [19]:
print(e)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [20]:
print(e.shape)
print(e.dtype)

(3, 3)
float64


In [21]:
e[0:2,0:2] #How to print a sub-matrix

array([[1., 2.],
       [4., 5.]])

In [22]:
e[1:3,1:3]

array([[5., 6.],
       [8., 9.]])

In [23]:
e[1:,1:]

array([[5., 6.],
       [8., 9.]])

In [24]:
e[:2,:2]

array([[1., 2.],
       [4., 5.]])

In [0]:
#How to initial placeholders?
#In case we have more data to fill
#Let's create placeholders with 0
f = np.zeros((2))

In [26]:
print(f)

[0. 0.]


In [0]:
g = np.zeros((2,2))

In [28]:
print(g)

[[0. 0.]
 [0. 0.]]


In [0]:
h = np.zeros((3,3,3))

In [30]:
print(h)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [31]:
#Placeholders with one
i = np.ones((3,3))
print(i)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [0]:
i = np.ones((3,3)) * 10

In [33]:
print(i)

[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [34]:
j = np.full((3,3),7) #same as above just takes second value which is 7 here as a placeholder to put everywhere
print(j)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [35]:
k = np.eye(4,4)
print(k)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [36]:
l = np.random.random((3,3)) #gives you random values between 0 and 1 
print(l)

[[0.08168392 0.23449765 0.7823658 ]
 [0.90927087 0.14321341 0.23994682]
 [0.47371188 0.88677482 0.957299  ]]


In [37]:
l = np.random.random((3,3)) * 500
print(l)

[[418.16051857 435.06477011 273.7870398 ]
 [ 38.86614512 437.4634606  267.05846039]
 [321.5572429  436.56402875 189.15098417]]


In [0]:
#Mathematical Operations

In [39]:
m = np.random.random((3,3)) * 100
n = np.random.random((3,3)) * 200
print(m)
print(n)

[[40.91489073 23.37676138 62.89643162]
 [57.89682228 52.68665118 82.01776858]
 [23.82147205 57.41493984  0.87631105]]
[[ 47.67473162  92.26354966 137.52701199]
 [132.00961972  41.66998374  34.38750778]
 [181.63573467  53.50177761 150.57183995]]


In [40]:
print(m+n)

[[ 88.58962235 115.64031104 200.42344361]
 [189.906442    94.35663492 116.40527636]
 [205.45720671 110.91671745 151.448151  ]]


In [41]:
print(m-n)

[[  -6.75984089  -68.88678827  -74.63058037]
 [ -74.11279743   11.01666744   47.6302608 ]
 [-157.81426262    3.91316223 -149.69552889]]


In [42]:
print(m/n)

[[0.85820915 0.25336941 0.45733875]
 [0.43858033 1.26437897 2.3851036 ]
 [0.1311497  1.07314079 0.00581989]]


In [43]:
print(m*n)

[[1950.60643465 2156.82298488 8649.95830595]
 [7642.93749259 2195.45189801 2820.38665494]
 [4326.83057587 3071.80134305  131.94776745]]


In [44]:
m

array([[40.91489073, 23.37676138, 62.89643162],
       [57.89682228, 52.68665118, 82.01776858],
       [23.82147205, 57.41493984,  0.87631105]])

In [45]:
m**(1/2)

array([[6.39647487, 4.83495206, 7.93072706],
       [7.60899614, 7.2585571 , 9.05636619],
       [4.88072454, 7.57726467, 0.93611487]])

In [46]:
print(np.exp(m))

[[5.87639893e+17 1.42036013e+10 2.06810786e+27]
 [1.39402460e+25 7.61240484e+22 4.16739160e+35]
 [2.21581685e+10 8.60977006e+24 2.40202241e+00]]


In [47]:
o = np.array([[1,2],[3,4]])
np.exp(o)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [48]:
(2.71)**o

array([[ 2.71      ,  7.3441    ],
       [19.902511  , 53.93580481]])

In [49]:
p = np.array([[1,2],[3,4]])
q = np.array([[5,6],[7,8]])
print(p)
print("-----------------------")
print(q)
print("-----------------------")
print(np.dot(p,q))

[[1 2]
 [3 4]]
-----------------------
[[5 6]
 [7 8]]
-----------------------
[[19 22]
 [43 50]]


In [50]:
#Checking if two numpy arrays are same or not
#Working : It returns true for the index where values are equal
r = np.array([[1,2],[3,4]])
s = np.array([[5,6],[3,4]])
print(r)
print("-----------------------")
print(s)
print("-----------------------")
print(r==s)

[[1 2]
 [3 4]]
-----------------------
[[5 6]
 [3 4]]
-----------------------
[[False False]
 [ True  True]]


In [51]:
#Comparison of values
print(r>2)

[[False False]
 [ True  True]]


In [52]:
print(s<5)

[[False False]
 [ True  True]]


In [53]:
r = np.array([[1,2],[3,4]])
s = np.array([[5,6],[3,4]])
print(r)
print("-----------------------")
print(s)
print("-----------------------")

[[1 2]
 [3 4]]
-----------------------
[[5 6]
 [3 4]]
-----------------------


In [54]:
print(r.max())
print(s.max())

4
6


In [55]:
print(r.max(axis=0)) #0 axis is by defualt is y axis (columns)
print(r.max(axis=1)) #x - axis along the rows

[3 4]
[2 4]


In [56]:
print(s.max(axis=0)) #0 axis is by defualt is y axis (columns)
print(s.max(axis=1)) #x - axis along the rows

[5 6]
[6 4]


In [57]:
r = np.array([[1,2],[3,4]])
s = np.array([[5,6],[3,4]])
print(r)
print("-----------------------")
print(s)
print("-----------------------")

[[1 2]
 [3 4]]
-----------------------
[[5 6]
 [3 4]]
-----------------------


In [58]:
print("Sum of r matrix: ",r.sum())
print(r.sum(axis=1)) #Addition along the rows
print(r.mean()) #Sum of all values / total no of values 
print(r.mean(axis=1)) #Mean along the rows
print(r.mean(axis=0)) #Mean along columns

Sum of r matrix:  10
[3 7]
2.5
[1.5 3.5]
[2. 3.]


In [59]:
t = np.array([1,2,3,4,5,6,7,8,9,0])
u = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print("T matrix ------------->",t)
print("<------------------------>")
print("U matrix ------------->")
print(u)

T matrix -------------> [1 2 3 4 5 6 7 8 9 0]
<------------------------>
U matrix ------------->
[[1 2 3 4 5]
 [6 7 8 9 0]]


In [60]:
print(t>5)
v = t[t>5]
print(v)

[False False False False False  True  True  True  True False]
[6 7 8 9]


In [61]:
print(u>5)
w = u[u>5]
print(w)

[[False False False False False]
 [ True  True  True  True False]]
[6 7 8 9]


In [62]:
# Array Manipulations
# Transpose
x = np.array([[1,2,3],[4,5,6]])
print(x)
print("Shape of X",x.shape)
y = x.transpose()
print(y)
print("Shape of X Tranpose", y.shape)

[[1 2 3]
 [4 5 6]]
Shape of X (2, 3)
[[1 4]
 [2 5]
 [3 6]]
Shape of X Tranpose (3, 2)


In [64]:
z = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(z.reshape(2,6))
print(z.reshape(3,4))
print(z.reshape(4,3))
#print(z.reshape(2,2))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
